//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Movie
    {
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        
        public string Name { get; set; }

        [Required]
        public string Genre { get; set; }

        [Required]
        public System.DateTime releasedate { get; set; }

        [Required]
        public int numberinstocks { get; set; }
    }
}
